/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package at.schwandter.codedemo.ui;

import at.schwandter.codedemo.game.Board;
import at.schwandter.codedemo.game.EntryAlreadySetException;
import at.schwandter.codedemo.game.Game;
import at.schwandter.codedemo.game.Player;

import java.util.Scanner;

public class GameCLI {

    Board board;
    Game game;

    public GameCLI() {
        board = new Board(3);
        game = new Game(board);
    }

    public static void main(String[] args) {

        GameCLI gameCLI = new GameCLI();
        gameCLI.runGame();
    }

    public void drawBoard(Board board) {
        for (int row = 0; row < 3; row++) {
            StringBuilder line = new StringBuilder();
            for (int col = 0; col < 3; col++) {
                var entry = board.getEntry(row, col);
                String symbol = entry.isPresent() ? entry.get().toString() : " ";
                line.append(symbol).append(" ");
            }
            System.out.println(line);
        }
    }

    private void runGame() {

        Scanner in = new Scanner(System.in);

        while (!game.finished()) {
            newTurn(in, Player.X);
            newTurn(in, Player.O);
        }
    }

    private void newTurn(Scanner in, Player player) {


        while (true) {
            System.out.println("Player " + player + ", enter row (1-3)");
            int row = in.nextInt();
            System.out.println("Player " + player + ", enter column (1-3)");
            int col = in.nextInt();
            try {
                game.playerSet(player, internalIndex(row), internalIndex(col));
                break;
            } catch (EntryAlreadySetException e) {
                System.out.println("This field was already set, try another one");
            } finally {
                this.drawBoard(board);
            }
        }
        if (game.playerWon(player)) {
            System.out.println("Player won: " + player);
            System.exit(0);
        }

    }

    private int internalIndex(int row) {
        return row - 1;
    }
}
